language: c++
compiler:
    - gcc

before_install:
    # Add these so we can get a more up-to-date G++ and CMake, and SFML!
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo apt-add-repository ppa:sonkun/sfml-stable
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq g++-4.8
    - sudo apt-get install -qq cmake
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - sudo apt-get install libsfml-dev=2.0
    - sudo apt-get install libglew-dev
    - sudo apt-get install libopenal-dev
    - sudo apt-get install libsndfile-dev
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=0 -DCMAKE_CXX_FLAGS="-std=c++11 -Wno-c++11-narrowing" -DCMAKE_INSTALL_PREFIX=../installation ../
    - make install
    - cd lib
    - svn co http://svn.boost.org/svn/boost/tags/release/Boost_1_55_0/ boost --quiet
    - cd boost
    - ./bootstrap.sh --prefix=installation
    - ./b2 cxxflags="-std=c++1y" linkflags="-stdlib=libc++" variant=release link=static --with-filesystem --with-system install -d0
    - cd ../..

before_script:
    - mkdir build && cd build
    - cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=RELEASE -DSTATIC_BUILD=1 -DCMAKE_CXX_FLAGS="-std=c++1y -isystem ../lib/boost" -DSFML_ROOT="lib/SFML/installation" -DBOOST_ROOT="lib/boost/installation" ../
script:
    - make
after_script:
    - ls

branches:
  only:
    - master

notifications:
    email: false
